
project_id = "eduforge-ai"
[functions.generate-educational-content]
verify_jwt = true

[functions.validate-educational-content]
verify_jwt = true

[functions.synthesize-education-prompt]
verify_jwt = true

[functions.content-generation-stream]
verify_jwt = true

