// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwijuclfikpacbxlphbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aWp1Y2xmaWtwYWNieGxwaGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTM0OTksImV4cCI6MjA2MzI2OTQ5OX0.qX2fTewwROqmQNAh25Qq-McWT4hXIZPFLRYnDQLHtrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);